# Generated by Django 4.2.30 on 2026-04-15 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_index", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "block_questions",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("specialty", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=10)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
            ],
            options={
                "db_table": "providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("description", models.TextField(blank=True, default="")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single_choice", "Single Choice"),
                            ("multiple_choice", "Multiple Choice"),
                            ("yes_no", "Yes/No"),
                            ("scale", "Scale"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("communication", "Communication"),
                            ("social_interaction", "Social Interaction"),
                            ("behavior", "Repetitive Behaviors"),
                            ("sensory", "Sensory Processing"),
                            ("motor", "Motor Skills"),
                            ("autonomy", "Autonomy"),
                        ],
                        max_length=30,
                    ),
                ),
                ("score_weight", models.FloatField(default=1.0)),
                ("age_min_months", models.PositiveIntegerField(default=0)),
                ("age_max_months", models.PositiveIntegerField(default=72)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "trigger_flag",
                    models.CharField(blank=True, default="", max_length=50),
                ),
            ],
            options={
                "db_table": "questions",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ScreeningSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_name", models.CharField(max_length=255)),
                ("child_first_name", models.CharField(max_length=255)),
                ("child_age_months", models.PositiveIntegerField()),
                (
                    "child_sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "respondent_role",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("main_concerns", models.JSONField(blank=True, default=list)),
                ("address", models.CharField(blank=True, default="", max_length=500)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("city", models.CharField(blank=True, default="", max_length=255)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "screening_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=50)),
                ("score", models.IntegerField(default=0)),
                ("is_red_flag", models.BooleanField(default=False)),
                ("order_index", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="screening.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_options",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="QuestionBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("age_min_months", models.PositiveIntegerField(default=0)),
                ("age_max_months", models.PositiveIntegerField(default=72)),
                ("is_core", models.BooleanField(default=True)),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="blocks",
                        through="screening.BlockQuestion",
                        to="screening.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_blocks",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="blockquestion",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="screening.questionblock",
            ),
        ),
        migrations.AddField(
            model_name="blockquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="screening.question"
            ),
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("global_score", models.FloatField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recommendation_level",
                    models.CharField(
                        choices=[
                            ("monitor", "Monitor"),
                            ("pediatric_consultation", "Pediatric Consultation"),
                            ("specialist_consultation", "Specialist Consultation"),
                            ("urgent_referral", "Urgent Referral"),
                        ],
                        max_length=30,
                    ),
                ),
                ("red_flags", models.JSONField(default=list)),
                ("domain_scores", models.JSONField(default=dict)),
                ("ai_summary", models.TextField(blank=True, default="")),
                ("ai_confidence_notes", models.JSONField(blank=True, default=list)),
                ("explanation_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="screening.screeningsession",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_results",
            },
        ),
        migrations.AlterUniqueTogether(
            name="blockquestion",
            unique_together={("block", "question")},
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_value", models.CharField(blank=True, default="", max_length=255)),
                ("computed_score", models.FloatField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screening.question",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="screening.questionoption",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="screening.screeningsession",
                    ),
                ),
            ],
            options={
                "db_table": "answers",
                "unique_together": {("session", "question")},
            },
        ),
    ]
