# Generated by Django 5.1.14 on 2026-04-12 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('_api_key', models.TextField(blank=True, db_column='api_key', default='')),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(choices=[(1, 'Principal'), (2, 'Fallback'), (3, 'Tertiaire')], default=1)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_day', models.IntegerField(default=500)),
                ('requests_today', models.IntegerField(default=0)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_healthy', models.BooleanField(default=True)),
                ('consecutive_errors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
